### PR TITLE
Changes in import of Qt modules

### LINKED ISSUE #230: rqt_joint_trajectory_controller needs a Kinetic update
trying to instantiate it inside rqt_gui on Xenial produces:

```
RosPluginProvider.load(rqt_joint_trajectory_controller/JointTrajectoryController) exception raised in __builtin__.__import__(rqt_joint_trajectory_controller.joint_trajectory_controller, [JointTrajectoryController]):
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 77, in load
    module = __builtin__.__import__(attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_joint_trajectory_controller/joint_trajectory_controller.py", line 35, in <module>
    from python_qt_binding.QtGui import QWidget, QFormLayout
ImportError: cannot import name QWidget
```

### PR DESCRIPTION
**Pull request by carlosjoserg**
RQt supports Qt5 in the Kinetic release (see the migration guide
http://wiki.ros.org/kinetic/Migration). In Qt5, QWidget and QFormLayout are
found in QtWidgets, see this ROS answer:
http://answers.ros.org/question/235126/import-issues-in-ros-kinetic-rqt/

Fixes #230 

I attach to the PR an Screenshot of it working on 16.04/Kinetic:
rqt_jtc

### CODE REVIEW

**Comment by bmagyar** [comment]
Hi Carlos,
I've tested it, seems all good. Thanks for the fix!

**Comment by wjwwood** [comment]
Thanks @carlosjoserg! @bmagyar any chance of getting this released this week (or anytime soon if that's not possible)?

**Comment by bmagyar** [comment]
Thanks for the reminder, I wanted to release it fast but forgot...

1-2 hours from now and it's out!

**Comment by wjwwood** [comment]
Thanks!
