### ISSUE TITLE
missing dependency in velocity_controllers on urdf is breaking build

### ISSUE THREAD

**Issue by tfoote** [ros-controls/ros_controllers#150]
I believe it was relying on an implicit dependency that has been cleaned up. 

http://jenkins.ros.org/view/IbinS32/job/ros-indigo-velocity-controllers_binarydeb_saucy_i386/25/console

```
[ 33%] Building CXX object CMakeFiles/velocity_controllers.dir/src/joint_velocity_controller.cpp.o
/usr/lib/ccache/c++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"velocity_controllers\" -Dvelocity_controllers_EXPORTS -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -O2 -g -DNDEBUG -fPIC -I/tmp/buildd/ros-indigo-velocity-controllers-0.9.0-0saucy-20141102-0505/include -I/opt/ros/indigo/include    -o CMakeFiles/velocity_controllers.dir/src/joint_velocity_controller.cpp.o -c /tmp/buildd/ros-indigo-velocity-controllers-0.9.0-0saucy-20141102-0505/src/joint_velocity_controller.cpp
/usr/bin/cmake -E cmake_progress_report /tmp/buildd/ros-indigo-velocity-controllers-0.9.0-0saucy-20141102-0505/obj-i686-linux-gnu/CMakeFiles 4
[ 66%] Building CXX object CMakeFiles/velocity_controllers.dir/src/joint_position_controller.cpp.o
/usr/lib/ccache/c++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"velocity_controllers\" -Dvelocity_controllers_EXPORTS -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -O2 -g -DNDEBUG -fPIC -I/tmp/buildd/ros-indigo-velocity-controllers-0.9.0-0saucy-20141102-0505/include -I/opt/ros/indigo/include    -o CMakeFiles/velocity_controllers.dir/src/joint_position_controller.cpp.o -c /tmp/buildd/ros-indigo-velocity-controllers-0.9.0-0saucy-20141102-0505/src/joint_position_controller.cpp
In file included from /tmp/buildd/ros-indigo-velocity-controllers-0.9.0-0saucy-20141102-0505/src/joint_position_controller.cpp:43:0:
/tmp/buildd/ros-indigo-velocity-controllers-0.9.0-0saucy-20141102-0505/include/velocity_controllers/joint_position_controller.h:70:24: fatal error: urdf/model.h: No such file or directory
 #include <urdf/model.h>
                        ^
compilation terminated.
```

**Comment by adolfo-rt** [comment]
I believe #151 should fix it. I also took the opportunity to make other dependencies explicit, that could cause trouble in the future. Pre-release tests did not catch this because they don't build in isolation as the buildfarm does.

**Comment by adolfo-rt** [comment]
https://github.com/ros/rosdistro/pull/6190
