### PR TITLE
Revert cmake include catkin_INCLUDE_DIRS as system

### PR DESCRIPTION
**Pull request by matthew-reynolds**
PR #315 changed the `include_directories()` of `diff_drive_controller`'s `CMakeLists.txt` to include catkin includes as SYSTEM.

This was done to suppresses compilation errors from upstream packages. However, it also mangles the header search list which causes issues with cross-compilation with (at least) GCC 6.1.1. A more thorough explanation can be found in [this Stack Overflow answer](https://stackoverflow.com/a/37218954/1932358), but in short, specifying `-isystem` breaks GCC's use of `#include_next` for system headers such as `cmath` and `cstdlib`.

Specifying `include_directories(SYSTEM ${catkin_INCLUDE_DIRS})` doesn't seem to be a common patttern in ROS packages. In fact, of the 147 packages resulting from `$ rosinstall_generator robot ros_control ros_controllers`, `diff_drive_controller` is the only package which does this (and consequently is the only package breaking my cross-compilation :stuck_out_tongue:).

### CODE REVIEW

**Review by mathias-luedtke — APPROVED** [review]

**Comment by efernandez** [comment]
Fair enough. Thanks for the PR @Matthew-Reynolds .

This was introduced in https://github.com/ros-controls/ros_controllers/commit/3c82ca78c7eccf56ac32d4239f8932e5724305e5
